# Environment Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:\\Users\\Ric\\.gradle\\jdks\\eclipse_adoptium-21-amd64-windows.2

minecraft_version=1.21.1
loader_version=0.16.14
fabric_version=0.116.17+1.21.1
loom_version=1.9.2

# Mod Properties
mod_id=storage_central
mod_name=Storage Central
mod_license=Apache-2.0
mod_version=1.26.9.9
mod_group_id=com.retiredroca.storagecentral
mod_authors=Retired Roca